import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1786643208117 implements MigrationInterface {
    name = 'InitSchema1786643208117'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('SUPERADMIN', 'ADMIN', 'USER')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying(255) NOT NULL, "username" character varying(30) NOT NULL, "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'USER', "isActive" boolean NOT NULL DEFAULT true, "isEmailVerified" boolean NOT NULL DEFAULT false, "hashedRefreshToken" character varying, "nameChangedAt" TIMESTAMP WITH TIME ZONE, "usernameChangedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subcategories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "categoryId" uuid NOT NULL, "name" character varying(100) NOT NULL, "iconPath" character varying, "displayOrder" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_793ef34ad0a3f86f09d4837007c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d1fe096726c3c5b8a500950e44" ON "subcategories" ("categoryId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_45aa12007713728e241d091775" ON "subcategories" ("categoryId", "name") `);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying(100) NOT NULL, "iconPath" character varying, "displayOrder" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_8b0be371d28245da6e4f4b61878" UNIQUE ("name"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."kyc_verifications_documenttype_enum" AS ENUM('CITIZENSHIP', 'PASSPORT')`);
        await queryRunner.query(`CREATE TYPE "public"."kyc_verifications_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "kyc_verifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid NOT NULL, "documentType" "public"."kyc_verifications_documenttype_enum" NOT NULL, "citizenshipFrontPath" character varying, "citizenshipBackPath" character varying, "passportPath" character varying, "permanentAddress" jsonb NOT NULL, "temporaryAddress" jsonb, "status" "public"."kyc_verifications_status_enum" NOT NULL DEFAULT 'PENDING', "rejectionReason" text, "reviewedBy" uuid, "reviewedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_f71e34495dae27087b5773b35b4" UNIQUE ("userId"), CONSTRAINT "PK_57b7c6b141dd225ce5dc95d7fb0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f71e34495dae27087b5773b35b" ON "kyc_verifications" ("userId") `);
        await queryRunner.query(`CREATE TABLE "bank_details" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid NOT NULL, "bankName" character varying(255) NOT NULL, "accountHolderName" character varying(255) NOT NULL, "accountNumber" text NOT NULL, "branch" text NOT NULL, "swiftCode" text, CONSTRAINT "UQ_d566e3c5f9b1b1c497d709c1fcc" UNIQUE ("userId"), CONSTRAINT "PK_ddbbcb9586b7f4d6124fe58f257" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "filePath" character varying NOT NULL, "originalFilename" character varying NOT NULL, "mimeType" character varying NOT NULL, "sizeBytes" integer NOT NULL, "displayOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_20bf02e97d9e2fb1704f04b4513" UNIQUE ("productId", "displayOrder"), CONSTRAINT "PK_1974264ea7265989af8392f63a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b367708bf720c8dd62fc683316" ON "product_images" ("productId") `);
        await queryRunner.query(`CREATE TYPE "public"."products_condition_enum" AS ENUM('NEW', 'LIKE_NEW', 'USED_GOOD', 'USED_FAIR', 'FOR_PARTS')`);
        await queryRunner.query(`CREATE TYPE "public"."products_status_enum" AS ENUM('DRAFT', 'SUBMITTED', 'REJECTED', 'APPROVED', 'PENDING', 'ACTIVE', 'CLOSED', 'AWAITING_PAYMENT', 'SETTLED', 'PAYMENT_FAILED', 'ABANDONED', 'WITHDRAWN')`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "ownerId" uuid NOT NULL, "title" character varying(150) NOT NULL, "description" text NOT NULL, "specifications" text, "categoryId" uuid NOT NULL, "subcategoryId" uuid NOT NULL, "condition" "public"."products_condition_enum" NOT NULL, "status" "public"."products_status_enum" NOT NULL DEFAULT 'DRAFT', "basePrice" numeric(12,2) NOT NULL, "biddingStartPrice" numeric(12,2) NOT NULL, "instantBuyPrice" numeric(12,2) NOT NULL, "currency" character varying(10) NOT NULL DEFAULT 'NPR', "biddingDurationHours" integer NOT NULL DEFAULT '72', "currentHighestBid" numeric(12,2), "currentHighestBidderId" uuid, "biddingStartedAt" TIMESTAMP WITH TIME ZONE, "biddingEndsAt" TIMESTAMP WITH TIME ZONE, "viewCount" integer NOT NULL DEFAULT '0', "submittedAt" TIMESTAMP WITH TIME ZONE, "reviewedById" uuid, "reviewedAt" TIMESTAMP WITH TIME ZONE, "rejectionReason" character varying, "locationProvince" character varying, "locationDistrict" character varying, "locationArea" character varying, "winningBidId" uuid, "closedAt" TIMESTAMP WITH TIME ZONE, "settledAt" TIMESTAMP WITH TIME ZONE, "abandonedAt" TIMESTAMP WITH TIME ZONE, "withdrawnAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_663aa9983fd61dfc310d407d4d" ON "products" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff56834e735fa78a15d0cf2192" ON "products" ("categoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7527f75cb36bea4b7f2b86f7d1" ON "products" ("subcategoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1846199852a695713b1f8f5e9a" ON "products" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3bc014be6177ded36911df7db5" ON "products" ("categoryId", "subcategoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bca32e7e2b877bcaae255805c3" ON "products" ("ownerId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_58075ba759b7738eb2eac5a9af" ON "products" ("status", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."bids_paymentstatus_enum" AS ENUM('NOT_RESPONSIBLE', 'PENDING', 'CONFIRMED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TYPE "public"."bids_paymentconfirmationmethod_enum" AS ENUM('ADMIN_MANUAL', 'BANK_API')`);
        await queryRunner.query(`CREATE TABLE "bids" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "productId" uuid NOT NULL, "bidderId" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, "placedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "previousHighestAmount" numeric(12,2), "wasFirstBid" boolean NOT NULL DEFAULT false, "isOriginalWinner" boolean NOT NULL DEFAULT false, "fallbackRank" integer NOT NULL DEFAULT '0', "isCurrentlyPaymentResponsible" boolean NOT NULL DEFAULT false, "isInstantBuy" boolean NOT NULL DEFAULT false, "paymentStatus" "public"."bids_paymentstatus_enum" NOT NULL DEFAULT 'NOT_RESPONSIBLE', "paymentDeadline" TIMESTAMP WITH TIME ZONE, "paymentConfirmedAt" TIMESTAMP WITH TIME ZONE, "paymentConfirmedById" uuid, "paymentConfirmationMethod" "public"."bids_paymentconfirmationmethod_enum", "paymentWarningSentAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_7950d066d322aab3a488ac39fe5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ed46f16a2ffae8257bf8524956" ON "bids" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fe34abd3aeb153efaea7a03c67" ON "bids" ("bidderId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b4e27104205a2f5aa6a71746dc" ON "bids" ("productId") WHERE "isCurrentlyPaymentResponsible" = true`);
        await queryRunner.query(`CREATE INDEX "IDX_8b351ea3618d54fd447818fb90" ON "bids" ("productId", "fallbackRank") `);
        await queryRunner.query(`CREATE INDEX "IDX_cd25f308f3161e81b7ce022662" ON "bids" ("paymentStatus", "paymentDeadline") `);
        await queryRunner.query(`CREATE INDEX "IDX_f76ca8600d0dd4774ac6fb3676" ON "bids" ("bidderId", "placedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_2616414c161d4309eb48abc015" ON "bids" ("productId", "amount") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('PENDING', 'SUCCESS', 'FAILED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_deliveryzone_enum" AS ENUM('INSIDE_VALLEY', 'OUTSIDE_VALLEY')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "productId" uuid NOT NULL, "winnerUserId" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, "referenceLabel" character varying(30) NOT NULL, "terminalId" character varying(16) NOT NULL, "qrString" text, "qrMessage" text, "websocketUrl" text, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'PENDING', "fonepayTraceId" character varying, "paymentMessage" character varying, "paymentDeadline" TIMESTAMP WITH TIME ZONE NOT NULL, "deliveryZone" "public"."payments_deliveryzone_enum" NOT NULL, "deliveryCharge" numeric(10,2) NOT NULL, "sellerPaidAt" TIMESTAMP WITH TIME ZONE, "sellerPaidById" uuid, "sellerPayoutAmount" numeric(12,2), "sellerCommissionPercent" numeric(5,2), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_80a2b377fa57b59dc5c0e138ef" ON "payments" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_df3c369970714c014a4bcd6b01" ON "payments" ("winnerUserId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_885b048d8480daa62900ddf01e" ON "payments" ("referenceLabel") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4eb1e967f6cc268c5a47d895a7" ON "payments" ("productId") WHERE "status" = 'PENDING'`);
        await queryRunner.query(`CREATE INDEX "IDX_dcfc63d678037d5ed27778bb6b" ON "payments" ("winnerUserId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_99334eb0755ef43771f9ef80c0" ON "payments" ("productId", "status") `);
        await queryRunner.query(`CREATE TABLE "email_verification_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token_hash" character varying NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_417a095bbed21c2369a6a01ab9a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_email_verification_tokens_user_id" ON "email_verification_tokens" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_email_verification_tokens_token_hash" ON "email_verification_tokens" ("token_hash") `);
        await queryRunner.query(`CREATE TABLE "password_reset_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token_hash" character varying NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_d16bebd73e844c48bca50ff8d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_password_reset_tokens_user_id" ON "password_reset_tokens" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_password_reset_tokens_token_hash" ON "password_reset_tokens" ("token_hash") `);
        await queryRunner.query(`CREATE INDEX "idx_password_reset_tokens_expires_at" ON "password_reset_tokens" ("expires_at") `);
        await queryRunner.query(`CREATE TABLE "pending_email_changes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "new_email" character varying(255) NOT NULL, "token_hash" character varying NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_2257e65ef4e5517f7eb450f6bf4" UNIQUE ("user_id"), CONSTRAINT "PK_974a0acecd615af6eb2db57e170" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_pending_email_changes_user_id" ON "pending_email_changes" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_pending_email_changes_token_hash" ON "pending_email_changes" ("token_hash") `);
        await queryRunner.query(`CREATE TYPE "public"."user_rewards_sellertier_enum" AS ENUM('BRONZE', 'SILVER', 'GOLD', 'PLATINUM', 'DIAMOND')`);
        await queryRunner.query(`CREATE TABLE "user_rewards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid NOT NULL, "buyerPoints" integer NOT NULL DEFAULT '0', "sellerPoints" integer NOT NULL DEFAULT '0', "sellerTier" "public"."user_rewards_sellertier_enum" NOT NULL DEFAULT 'BRONZE', CONSTRAINT "UQ_d538de4678c82491e5a8a8a5834" UNIQUE ("userId"), CONSTRAINT "PK_86078010f64a891601beef7c54f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d538de4678c82491e5a8a8a583" ON "user_rewards" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."points_transactions_type_enum" AS ENUM('BUYER', 'SELLER')`);
        await queryRunner.query(`CREATE TABLE "points_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid NOT NULL, "type" "public"."points_transactions_type_enum" NOT NULL, "delta" integer NOT NULL, "reason" text NOT NULL, "referenceId" uuid, CONSTRAINT "PK_b368729603fe6bc50fdb6750b33" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac28945bbf0761c3e6fe0c816b" ON "points_transactions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5fa6b575b1f20bf2a46235ae22" ON "points_transactions" ("userId", "createdAt") `);
        await queryRunner.query(`ALTER TABLE "subcategories" ADD CONSTRAINT "FK_d1fe096726c3c5b8a500950e448" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_b367708bf720c8dd62fc6833161" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bids" ADD CONSTRAINT "FK_ed46f16a2ffae8257bf85249562" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bids" ADD CONSTRAINT "FK_fe34abd3aeb153efaea7a03c676" FOREIGN KEY ("bidderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_80a2b377fa57b59dc5c0e138ef3" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_df3c369970714c014a4bcd6b01a" FOREIGN KEY ("winnerUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_df3c369970714c014a4bcd6b01a"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_80a2b377fa57b59dc5c0e138ef3"`);
        await queryRunner.query(`ALTER TABLE "bids" DROP CONSTRAINT "FK_fe34abd3aeb153efaea7a03c676"`);
        await queryRunner.query(`ALTER TABLE "bids" DROP CONSTRAINT "FK_ed46f16a2ffae8257bf85249562"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_b367708bf720c8dd62fc6833161"`);
        await queryRunner.query(`ALTER TABLE "subcategories" DROP CONSTRAINT "FK_d1fe096726c3c5b8a500950e448"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5fa6b575b1f20bf2a46235ae22"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac28945bbf0761c3e6fe0c816b"`);
        await queryRunner.query(`DROP TABLE "points_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."points_transactions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d538de4678c82491e5a8a8a583"`);
        await queryRunner.query(`DROP TABLE "user_rewards"`);
        await queryRunner.query(`DROP TYPE "public"."user_rewards_sellertier_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pending_email_changes_token_hash"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pending_email_changes_user_id"`);
        await queryRunner.query(`DROP TABLE "pending_email_changes"`);
        await queryRunner.query(`DROP INDEX "public"."idx_password_reset_tokens_expires_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_password_reset_tokens_token_hash"`);
        await queryRunner.query(`DROP INDEX "public"."idx_password_reset_tokens_user_id"`);
        await queryRunner.query(`DROP TABLE "password_reset_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."idx_email_verification_tokens_token_hash"`);
        await queryRunner.query(`DROP INDEX "public"."idx_email_verification_tokens_user_id"`);
        await queryRunner.query(`DROP TABLE "email_verification_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99334eb0755ef43771f9ef80c0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dcfc63d678037d5ed27778bb6b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4eb1e967f6cc268c5a47d895a7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_885b048d8480daa62900ddf01e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df3c369970714c014a4bcd6b01"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_80a2b377fa57b59dc5c0e138ef"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_deliveryzone_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2616414c161d4309eb48abc015"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f76ca8600d0dd4774ac6fb3676"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd25f308f3161e81b7ce022662"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b351ea3618d54fd447818fb90"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4e27104205a2f5aa6a71746dc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe34abd3aeb153efaea7a03c67"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed46f16a2ffae8257bf8524956"`);
        await queryRunner.query(`DROP TABLE "bids"`);
        await queryRunner.query(`DROP TYPE "public"."bids_paymentconfirmationmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."bids_paymentstatus_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_58075ba759b7738eb2eac5a9af"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bca32e7e2b877bcaae255805c3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3bc014be6177ded36911df7db5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1846199852a695713b1f8f5e9a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7527f75cb36bea4b7f2b86f7d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff56834e735fa78a15d0cf2192"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_663aa9983fd61dfc310d407d4d"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TYPE "public"."products_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."products_condition_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b367708bf720c8dd62fc683316"`);
        await queryRunner.query(`DROP TABLE "product_images"`);
        await queryRunner.query(`DROP TABLE "bank_details"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f71e34495dae27087b5773b35b"`);
        await queryRunner.query(`DROP TABLE "kyc_verifications"`);
        await queryRunner.query(`DROP TYPE "public"."kyc_verifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."kyc_verifications_documenttype_enum"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45aa12007713728e241d091775"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1fe096726c3c5b8a500950e44"`);
        await queryRunner.query(`DROP TABLE "subcategories"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
    }

}
