export const SPECIFICATIONS_SEED: string[] = [
  'Condition',
  'Brand',
  'Model',
  'Color',
  'Size',
  'Material',
  'Weight',
  'Dimensions',
  'RAM',
  'Storage',
  'Processor',
  'Screen Size',
  'Battery Capacity',
  'Operating System',
  'Camera',
  'Connectivity',
  'Warranty',
  'Fuel Type',
  'Engine Capacity',
  'Mileage',
  'Transmission',
  'Year of Manufacture',
  'Fabric Type',
  'Gender',
  'Age Group',
  'Area (Sq. ft)',
  'Number of Bedrooms',
  'Number of Bathrooms',
  'Furnishing Status',
  'Author',
  'Publisher',
  'Language',
  'Edition',
  'Breed',
  'Power Source',
];
