export enum NotificationType {
  BID_PLACED_SELLER = 'BID_PLACED_SELLER',
  OUTBID = 'OUTBID',
  AUCTION_WON = 'AUCTION_WON',
  AUCTION_CLOSED_SELLER = 'AUCTION_CLOSED_SELLER',
  PAYMENT_WINDOW_EXPIRING = 'PAYMENT_WINDOW_EXPIRING',
  PAYMENT_FAILED_FALLBACK = 'PAYMENT_FAILED_FALLBACK',
  PAYMENT_FAILED_SELLER = 'PAYMENT_FAILED_SELLER',
  AUCTION_ABANDONED = 'AUCTION_ABANDONED',
  PAYMENT_CONFIRMED_SELLER = 'PAYMENT_CONFIRMED_SELLER',
  PAYMENT_CONFIRMED_BUYER = 'PAYMENT_CONFIRMED_BUYER',
}
